# Site settings
title: "Zombyte Blog"
email: noreply@zombyte.net
description: "A blog for Zombyte variety of ranting and cookies"
baseurl: ""
url: "https://zombyte.net"
title_description: "Things and Cookies"
title_image: "http://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
# google_analytics: "UA-20365477-4"
# disqus_account: zombyte
github_repository: https://github.com/zombyte/zombyte.github.io
# addthis_id: ra-513c6fa83da6ec67
# post_limit: 5

# Social usernames/URLs
twitter_username: zombyte_13
github_username:  zombyte
# linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
# google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
# stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/

# Footer
footer_left: "Articles  by <a href=\"https://twitter.com/zombyte_13\">Zombyte</a> and presented with <a href=\"https://github.com/jacobtomlinson/carte-noire\">Carte-Noire</a>."
footer_right: "Jekyll Theme: <a href=\"https://github.com/jacobtomlinson/carte-noire\">Carte-Noire</a>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
